#!/usr/bin/env sh

spacebar -m config display main
spacebar -m config position top
spacebar -m config height 30
spacebar -m config padding_left 10
spacebar -m config padding_right 10
spacebar -m config spacing_left 20
spacebar -m config spacing_right 20
spacebar -m config spaces on
spacebar -m config display_separator off
spacebar -m config clock on
spacebar -m config power on
spacebar -m config text_font "Migu 1P:Regular:15.0"
spacebar -m config icon_font "Noto Emoji:Regular:15.0"
spacebar -m config background_color 0xff1a1b26
spacebar -m config foreground_color 0xffa9b1d6
spacebar -m config clock_format " %H:%M"
spacebar -m config clock_icon "⏰"
spacebar -m config clock_icon_color 0xff7aa2f7
spacebar -m config spaces_for_all_displays on
spacebar -m config space_icon_strip 1 2 3 4 5 6 7 8 9 10
spacebar -m config space_icon_color 0xff73daca
spacebar -m config space_icon_color_secondary 0xffa9b1d6
spacebar -m config space_icon_color_tertiary 0xffa9b1d6
spacebar -m config power_icon_strip 🔋 🔌
spacebar -m config power_icon_color 0xff7aa2f7
spacebar -m config battery_icon_color 0xff7aa2f7
