#!/usr/bin/env sh

yabai -m config external_bar main:32:0

yabai -m config mouse_modifier cmd
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

yabai -m config layout bsp
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 6

yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus on
yabai -m config window_topmost on
yabai -m config window_shadow float
yabai -m config window_placement second_child
yabai -m config window_border off

yabai -m config auto_balance on
yabai -m config split_ratio 0.5
