#!/usr/bin/env sh

yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus on
yabai -m config window_topmost on
yabai -m config window_shadow float
yabai -m config window_placement second_child

yabai -m config layout bsp
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 6
